force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <description>Cars</description>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Car owner</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Car_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car Type</label>
    <referenceTo>Car_Type__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Type__c/Car_Type__c.object-meta.xml
<CustomObject>
    <label>Car Type</label>
    <nameField>
        <label>Car Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    private static List<Car__c> createCars(Integer numItems) {
        List<Account> accounts = new List<Account>();
        for(Integer i=0;i<numItems;i++) {
        	Account newAccount = new Account();
        	newAccount.Name = 'Test'+i;
            accounts.add(newAccount);
        }
        insert accounts;
        
        List<Car_Type__c> types = new List<Car_Type__c>();
        for (Integer i=0;i<numItems;i++) {
        	Car_Type__c newType = new Car_Type__c();
        	newType.Name = 'Test'+i;
            types.add(newType);
        }        
		insert types;
        
        List<Car__c> cars = new List<Car__c>();
        for (Integer i=0;i<numItems;i++) {
        	Car__c newCar = new Car__c();
        	newCar.Name = 'Test'+i;
            newCar.Account__c = accounts[i].id;
            newCar.Car_Type__c = types[i].id;
            cars.add(newCar);
        }
        return cars;
    }

    public static List<Car__c> createCarsWithTypesAndAccounts(Integer numItems, Boolean doInsert) {
        
        List<Car__c> cars = createCars(numItems);
        
        if (doInsert) {        
		    insert cars;
        }
        
        return cars;
    }

	public static List<Car__c> createCarsWithTypesAndAccounts(Integer numItems) {

        List<Car__c> cars = createCars(numItems);
        
		insert cars;
        
        return cars;
    }
    
    public static List<Car_Type__c> createCarTypes(Integer numItems) {
    
        List<Car_Type__c> types = new List<Car_Type__c>();
        for (Integer i=0;i<numItems;i++) {
        	Car_Type__c newType = new Car_Type__c();
        	newType.Name = 'Test'+i;
            types.add(newType);
        }        
		insert types;
                
        return types;
    }
        
}