force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <description>Cars</description>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Car owner</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Car_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car Type</label>
    <referenceTo>Car_Type__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Picture__c.field-meta.xml
<CustomField>
    <fullName>Picture__c</fullName>
    <description>Car image url</description>
    <label>Picture</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Car_Type__c/Car_Type__c.object-meta.xml
<CustomObject>
    <label>Car Type</label>
    <nameField>
        <label>Car Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CarDataService.cls
public with sharing class CarDataService {

    @AuraEnabled(cacheable=true)
    public static List<Car_Type__c> getCarTypes() {
        List<Car_Types> carTypes;
        try {
            carTypes = [SELECT Name, Id FROM Car_Type__c WITH SECURITY_ENFORCED ORDER BY Name];
        }
        catch(System.QueryException qe) {
            System.debug(qe.getMessage());
        }
        return carTypes;
    }

    @AuraEnabled(cacheable=true)
    public static List<Car__c> getCars(String carTypeId) {
        // Without a carTypeId, the full list is queried
        List<Car__c> cars;
        try {
            String query = 'SELECT '
                     + 'Name, Description__c, Geolocation__Latitude__s, '
                     + 'Geolocation__Longitude__s, Picture__c, Account__r.Name, '
                     + 'Car_Type__c, Car_Type__r.Name '
                     + 'FROM Car__c';
            if (String.isNotBlank(carTypeId)) {
                query += ' WHERE Car_Type__c = :carTypeId';
            }
            query += ' WITH SECURITY_ENFORCED ';
            cars = System.Database.query(query);
        } 
        catch(System.QueryException qe) {
            System.debug(qe.getMessage());
        }  
        return cars;
    }
}